model:
  type: surfformerv2
  masif:
    resolution: residue
    nearest_neighbors:
      res_res: 4              # 4 is better than 16
      res_point: 1
    atom_dims: 16
    res_dims: 16              # Number of atom types and dimension of resulting chemical features, default: 6
    hidden_dims: 16           # Number of input features, default: 8
    ori_dim: 16               # Number of hidden units for the orientation score MLP
    radius: 9.0               # Radius to use for the convolution
    dropout: 0.0
    n_layers: 1               # default: 1
  transformer:
    ape: False
    n_heads: 8
    n_layers: 1
    dropout: 0.1
  partner:
    input: surface
    feat_dim:
  patch_setup:
    patch_ratio: 0.02
    n_patches: 500
    n_pts_per_patch: 50
  loss_setup:
    soft: False
    type: binary_cross_entropy
    coarse: 1.0
    fine: 0.0
  use_plm: False

dataset:
  processed_dir: ./data/processed
  use_plm: False
  relax_struct: False
  pred_struct: False
  surface:
    resolution: 1.0    # Resolution of the generated point cloud
    distance: 1.05     # Distance parameter in structures generation
    variance: 0.1      # Variance parameter in structures generation
    sup_sampling: 10   # Sup-sampling ratio around atoms, default: 20
    intf_cutoff: 4    # threshold to determine the interface
  intf_cutoff_res: 6

train:
  loss_weights:
    ep: 1.0
  max_iters: 50_000
  val_freq: 500
  batch_size: 16   # larger batch size is better. 16 > 8
  seed: 2023
  max_grad_norm: 100.0
  eval_resolution: patch
  max_pts: 50000
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 5
    min_lr: 5.e-6

